### ISSUE TITLE
flextable 0.6.0 changed unicode display

### ISSUE THREAD

**Issue by phil-o** [davidgohel/flextable#268]
version 0.6.0  and 0.6.0 of flextable (from CRAN) don't display unicode symbols in table data.

```
devtools::install_version('flextable', version='0.6.0')
library(flextable)
flextable(data.frame(c('\U2265 4.7')))
```
version 0.5.9 and 0.5.10 display the greater-than-equal sign, right-aligns the cell.
![image](https://user-images.githubusercontent.com/46729957/101568139-35294f00-3a26-11eb-8036-2414f40dc50c.png)

version 0.5.11 displays the greater-than-equal sign, left-aligns the cell.
![image](https://user-images.githubusercontent.com/46729957/101568274-702b8280-3a26-11eb-8e75-059342776470.png)

version 0.6.0 and 0.6.1 display the equal sign, INSTEAD of greater-than-equal, left-aligns the cell
![image](https://user-images.githubusercontent.com/46729957/101568539-d7493700-3a26-11eb-94b7-52657393ce6e.png)

```
> sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flextable_0.6.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        digest_0.6.27     R6_2.5.0          magrittr_2.0.1   
 [5] evaluate_0.14     zip_2.1.1         rlang_0.4.9       gdtools_0.2.2    
 [9] uuid_0.1-4        data.table_1.13.2 xml2_1.3.2        rmarkdown_2.5    
[13] tools_4.0.1       officer_0.3.15    xfun_0.19         compiler_4.0.1   
[17] systemfonts_0.3.2 base64enc_0.1-3   htmltools_0.5.0   knitr_1.30 


```

**Comment by davidgohel** [comment]
I think this is related to your platform; on a platform whose encoding is UTF-8, I got:

```
library(flextable)
library(magrittr)
flextable(data.frame(colname = c('≥ 4.7', '\U2265 4.7'))) %>% 
  font(font = "Courier", part = "all")
```

<img width="758" alt="Capture d’écran 2020-12-09 à 10 02 01" src="https://user-images.githubusercontent.com/4331618/101608089-9b51aa00-3a05-11eb-9dbb-d9d187575754.png">

**Comment by phil-o** [comment]
I'm sure it's related to the platform, but when the display changes and the ONLY thing I change is the version of flextable installed, it also seems related to flextable!

**Comment by davidgohel** [comment]
Sorry if you misunderstood what I was saying. Yes, it's a bug or at least something that may be documented. That's why I added the tag "bug".

**Comment by ndevln** [comment]
Hi,

I am seeing the same problem. When testing flextable 0.6.1 the unicode symbol ↑ gets changed to <U+2191>. This is probably a Windows problem (like always). UTF-8 is just a pain on Windows. I will investigate further.

**Comment by bishun945** [comment]
I had the similar issuse. 

Now `flextable` (v0.6.1) returns some unicode character such as `<U+5F20>` when my data.frame includes some **Chinese characters**.

``` r
library(flextable)
dt <- data.frame(
   A = c("张三", "李四"),
   B = c("Zhangsan", "Lisi")
)
flextable(dt)
```
It returns: 
![图片](https://user-images.githubusercontent.com/33533084/102729257-f15e1000-436a-11eb-8433-2266dd2970c4.png)

My `sessionInfo()` is:

```
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flextable_0.6.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        digest_0.6.25     R6_2.5.0          magrittr_1.5      evaluate_0.14     zip_2.1.1        
 [7] rlang_0.4.8       gdtools_0.2.2     uuid_0.1-4        data.table_1.13.2 xml2_1.3.2        rmarkdown_2.5    
[13] tools_3.6.2       officer_0.3.15    xfun_0.19.1       compiler_3.6.2    systemfonts_0.3.2 base64enc_0.1-3  
[19] htmltools_0.5.0   knitr_1.30    
```

**Comment by davidgohel** [comment]
This is the rendering I got @bishun945:

<img width="532" alt="Capture d’écran 2020-12-21 à 06 21 19" src="https://user-images.githubusercontent.com/4331618/102742254-c668c180-4354-11eb-9dd3-5bf0143dcad6.png">

I don't understand what your comment bring to the discussion.

**Comment by davidgohel** [comment]
thanks for the clue @ndevln.

Things should be solved with the latest github version (https://github.com/davidgohel/flextable/commit/5e0ebb39e8bb484148a23103b58cd2770afe83ee). Please let me know if still not working. It has only been tested on a French Windows system.

All cases you submitted are working ok now.

There is one case I have not solved yet. The following does not work:

```
library(tidyverse)
library(flextable)

tibble("Столбец1" = "Value1", Column2 = "Значение1") %>% flextable()
```

(but this works as a workaround):

```
tibble("zz" = "Value1", Column2 = "Значение1") %>% flextable() %>%
  set_header_labels(zz = "Столбец1") 
```

**Comment by davidgohel** [comment]
Closing the issue as no feedback

It probably means it's fixed now as nobody complained.

**Comment by timelyportfolio** [comment]
@davidgohel If helpful, I just ran across a similar issue today on Windows with `utf-8` encoded column names.   5e0ebb3 seems to solve the issue.  Thanks so much for all your work on `flextable` and other packages.

```r
library(flextable)

ft <- flextable(mtcars)

# works
set_header_labels(
  ft,
  values = structure(
    paste0(colnames(mtcars),"Δ"),
    names = colnames(mtcars)
  )
)
```

```r
# does not work
typology <- data.frame(
  col_keys = colnames(mtcars),
  top = colnames(mtcars),
  bottom = "Δ",
  check.names = FALSE,
  stringsAsFactors = FALSE
)
set_header_df(ft, typology)
```

```r
typology <- tibble::tibble( # try with tibble since better encoding handling
  col_keys = colnames(mtcars),
  top = colnames(mtcars),
  bottom = "Δ"
)
set_header_df(ft, typology)
```

```r
# fix for set_header_df
ft2 <- set_header_df(ft, typology)
# not generic but demonstrates how to fix the encoding issue
#   replace the utf-8 character with itself
ft2$header$content$content$data[2,] <-mapply(
  function(x,y) {
    x$txt <- y
    x
  },
  x = ft2$header$content$content$data[2,],
  y = "Δ",
  SIMPLIFY = FALSE
)

ft2
```

**Comment by phil-o** [comment]
The current github version is still not completely working on Windows 10. 

It is better - it handles unicode \Uxxxx codes, which was the original issue. It doesn't handle directly entered symbols properly though, which it does on David's UTF8 setup.

```
library(flextable)
library(magrittr)
flextable(data.frame(colname = c('≥ 4.7', '\U2265 4.7'))) %>% 
  font(font = "Courier", part = "all")
```
![image](https://user-images.githubusercontent.com/46729957/104137132-c6f1f680-53ee-11eb-9116-8d2f0a068c28.png)

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_2.0.1      flextable_0.6.2.010

loaded via a namespace (and not attached):
 [1] zip_2.1.1         Rcpp_1.0.5        compiler_4.0.3    prettyunits_1.1.1
 [5] base64enc_0.1-3   remotes_2.2.0     tools_4.0.3       uuid_0.1-4       
 [9] testthat_3.0.1    digest_0.6.27     pkgbuild_1.2.0    pkgload_1.1.0    
[13] evaluate_0.14     memoise_1.1.0     lifecycle_0.2.0   rlang_0.4.10     
[17] cli_2.2.0         rstudioapi_0.13   curl_4.3          xfun_0.20        
[21] xml2_1.3.2        officer_0.3.16    withr_2.3.0       knitr_1.30       
[25] desc_1.2.0        gdtools_0.2.3     fs_1.5.0          systemfonts_0.3.2
[29] devtools_2.3.2    rprojroot_2.0.2   glue_1.4.2        data.table_1.13.6
[33] R6_2.5.0          processx_3.4.5    fansi_0.4.1       rmarkdown_2.6    
[37] sessioninfo_1.1.1 callr_3.5.1       purrr_0.3.4       ps_1.5.0         
[41] ellipsis_0.3.1    htmltools_0.5.0   usethis_2.0.0     assertthat_0.2.1 
[45] crayon_1.3.4 
```

**Comment by davidgohel** [comment]
OK, thanks, I will use your use cases.

**Comment by davidgohel** [comment]
I'm afraid there's not much I can do. The problem is not limited to flextable, the issue is the same with kable, with a standard print, I tried several other packages, methods, etc. 

https://developer.r-project.org/Blog/public/2020/05/02/utf-8-support-on-windows/

If you want to use specific characters, it is better to use unicodes codes :

![screenshot](https://user-images.githubusercontent.com/4331618/104629338-a8fbee80-5699-11eb-9464-d453e0a6c202.png)


``````
---
title: "Untitled"
output:
  html_document: default
---


```{r echo=FALSE}
library(flextable)
library(magrittr)

dt <- data.frame(
   A = c("张三", "李四"),
   B = c("Zhangsan", "Lisi")
)
tab1 <- flextable(dt) %>%
  theme_box() %>%
  autofit()
tab1
knitr::kable(dt)
dt

dat <- data.frame(colname = c("≥ 4.7\u0394", "\U2265 4.7"))

tab2 <- flextable(dat) %>%
  theme_box() %>%
  autofit()
tab2
dat
```




``````


So, I am gonna close the issue as I don't think I can solve this. It's about Windows and R. The system is not able to print these characters in R for Windows unless they are defined with unicode codes.

**Comment by timelyportfolio** [comment]
Thanks @davidgohel for checking!  [`textutils::htmlEncode`](https://rdrr.io/cran/textutils/man/HTMLdecode.html) might be our friend here.  I'll do some quick tests and report back.
