### ISSUE TITLE
Merged cells do not print in Word

### ISSUE THREAD

**Issue by mjaniec2013** [davidgohel/flextable#48]
Used code from "Overview" [(https://davidgohel.github.io/flextable/articles/overview.html)], output DOCX attached.

```
library(flextable)
library(officer)

myft <- regulartable(
  head(mtcars), 
  col_keys = c("am", "carb", "gear", "mpg", "drat" ))
myft <- merge_v(myft, j = c("am", "carb") )
myft

doc <- read_docx()
doc <- body_add_flextable(doc, value = myft)
print(doc, target = "c:/temp/example.docx")
```

R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

[example.docx](https://github.com/davidgohel/flextable/files/1690330/example.docx)

**Comment by mjaniec2013** [comment]
Seems, merged cells are individually printed to DOCX, but not visible.

Content of individual merged cells becomes visible after changing width of the column. All merged cells have the same value.

**Comment by davidgohel** [comment]
Thanks. I remember having made the same mistake with ReporteRs, I will try to fix it soon.

Please add the `sessionInfo()` as explained in the guidelines of the issue template:

- [ ] the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example.

**Comment by mjaniec2013** [comment]
Complete sessionInfo() output:

```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dplyr_0.7.4        quantmod_0.4-12    TTR_0.23-2         xts_0.10-1         nortest_1.0-4      hydroGOF_0.3-10    fpp_0.5           
 [8] tseries_0.10-42    lmtest_0.9-35      expsmooth_2.3      fma_2.3            forecast_8.2       strucchange_1.5-1  sandwich_2.4-0    
[15] zoo_1.8-1          flextable_0.4.2    officer_0.2.1      docxtractr_0.2.0   magrittr_1.5       xml2_1.1.1         textreadr_0.7.0   
[22] stringr_1.2.0      stringdist_0.9.4.6 fastmatch_1.1-0    readxl_1.0.0      

loaded via a namespace (and not attached):
 [1] R.utils_2.6.0       assertthat_0.2.0    sp_1.2-7            cellranger_1.1.0    yaml_2.1.16         gdtools_0.1.6       pillar_1.1.0       
 [8] backports_1.1.2     lattice_0.20-35     glue_1.2.0          quadprog_1.5-5      automap_1.0-14      uuid_0.1-2          digest_0.6.14      
[15] colorspace_1.3-2    htmltools_0.3.6     R.oo_1.21.0         plyr_1.8.4          hydroTSM_0.5-1      timeDate_3042.101   pkgconfig_2.0.1    
[22] purrr_0.2.4         scales_0.5.0        intervals_0.15.1    gstat_1.1-5         tibble_1.4.1        ggplot2_2.2.1       nnet_7.3-12        
[29] lazyeval_0.2.1      maptools_0.9-2      evaluate_0.10.1     R.methodsS3_1.7.1   foreign_0.8-69      class_7.3-14        FNN_1.1            
[36] tools_3.4.3         data.table_1.10.4-3 munsell_0.4.3       zip_1.0.0           bindrcpp_0.2        compiler_3.4.3      e1071_1.6-8        
[43] spacetime_1.2-1     rlang_0.1.6         grid_3.4.3          base64enc_0.1-3     rmarkdown_1.8       gtable_0.2.0        fracdiff_1.4-2     
[50] reshape_0.8.7       curl_3.1            R6_2.2.2            knitr_1.19          bindr_0.1           rprojroot_1.3-2     stringi_1.1.6      
[57] parallel_3.4.3      Rcpp_0.12.14       
```

**Comment by davidgohel** [comment]
Thanks, could you install the github version, this should solve the issue.

**Comment by mjaniec2013** [comment]
Hello,

Installed from github and run once more. The table is still not correctly
saved to DOCX :(

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United
States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United
States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] flextable_0.4.2    docxtractr_0.2.0   magrittr_1.5       xml2_1.2.0
     textreadr_0.7.0    dplyr_0.7.4
 [7] stringr_1.2.0      stringdist_0.9.4.6 fastmatch_1.1-0    readxl_1.0.0
     officer_0.2.2.002  devtools_1.13.4

loaded via a namespace (and not attached):
 [1] zip_1.0.0           Rcpp_0.12.15        cellranger_1.1.0
compiler_3.4.3      pillar_1.1.0        git2r_0.21.0
 [7] bindr_0.1           R.methodsS3_1.7.1   R.utils_2.6.0
 base64enc_0.1-3     tools_3.4.3         digest_0.6.15
[13] uuid_0.1-2          evaluate_0.10.1     memoise_1.1.0
 tibble_1.4.1        pkgconfig_2.0.1     rlang_0.1.6
[19] curl_3.1            yaml_2.1.16         parallel_3.4.3
bindrcpp_0.2        withr_2.1.1         httr_1.3.1
[25] knitr_1.19          gdtools_0.1.6       rprojroot_1.3-2
 glue_1.2.0          data.table_1.10.4-3 R6_2.2.2
[31] rmarkdown_1.8       purrr_0.2.4         backports_1.1.2
 htmltools_0.3.6     assertthat_0.2.0    stringi_1.1.6
[37] R.oo_1.21.0

MJ

MJ

**Comment by davidgohel** [comment]
The github version is `> 0.4.2` but your installation has `0.4.2`

https://github.com/davidgohel/flextable/blob/master/DESCRIPTION#L4

**Comment by mjaniec2013** [comment]
This is what's installed using

devtools::install_github("davidgohel/flextable")


MJ

MJ

**Comment by mjaniec2013** [comment]
other attached packages:
 [1] flextable_0.4.3.0001


MJ

MJ

**Comment by davidgohel** [comment]
Sorry, this is what I get:

[example.docx](https://github.com/davidgohel/flextable/files/1709059/example.docx)

with that code: 

````
library(flextable)
library(officer)

myft <- regulartable(
  head(mtcars), 
  col_keys = c("am", "carb", "gear", "mpg", "drat" ))
myft <- merge_v(myft, j = c("am", "carb") )
myft

doc <- read_docx()
doc <- body_add_flextable(doc, value = myft)
print(doc, target = "example.docx")
````
