### ISSUE TITLE
htmltools_value Error: OpenSSL SSL_connect: Connection reset by peer in connection to gwfh.mranftl.com:443

### ISSUE THREAD

**Issue by hjia222** [davidgohel/flextable#525]
I encountered issue with htmltools_value() in R shiny. 
flextable_0.9.0

```
library(shiny)
library(flextable)
library(dplyr)

dat <- mtcars %>%
  mutate(car = rownames(.)) %>%
  select(car, everything())

ui <- fluidPage(
  titlePanel("mtcars"),
  sidebarLayout(
    sidebarPanel(
      sliderInput("mpg", "mpg Limit", min = 11, max = 33, value = 20)
    ),
    mainPanel(uiOutput("mtcars_ft"))
  )
)

server <- function(input, output) {
  output$mtcars_ft <- renderUI({
    req(input$mpg)
    filter(dat, mpg <= input$mpg) %>%
      flextable() %>%
      theme_vader() %>%
      autofit() %>%
      htmltools_value()
  })
}

# Run the application
shinyApp(ui = ui, server = server)
```

Listening on http://127.0.0.1:4088
Warning: Error in curl::curl_fetch_memory: OpenSSL SSL_connect: Connection reset by peer in connection to gwfh.mranftl.com:443 
  119: curl::curl_fetch_memory
  118: crul_fetch
  117: private$make_request
  116: cli$get
  115: get_gf
  114: <Anonymous>
  109: installed_gfonts
  107: avail_gfonts
  104: flextable_html_dependencies
  101: htmltools_value
  100: %>%
   99: renderUI [#4]
   98: func
   85: renderFunc
   84: output$mtcars_ft
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.0.10    flextable_0.9.0 shiny_1.7.4    

loaded via a namespace (and not attached):
 [1] tidyselect_1.2.0        xfun_0.37               bslib_0.4.2             fontquiver_0.2.1       
 [5] vctrs_0.5.2             generics_0.1.3          htmltools_0.5.4         utf8_1.2.2             
 [9] rlang_1.1.0             jquerylib_0.1.4         later_1.3.0             pillar_1.8.1           
[13] withr_2.5.0             DBI_1.1.3               httpcode_0.3.0          glue_1.6.2             
[17] gfonts_0.2.0            gdtools_0.3.2           uuid_1.1-0              lifecycle_1.0.3        
[21] ragg_1.2.5              zip_2.2.2               memoise_2.0.1           evaluate_0.20          
[25] knitr_1.42              fastmap_1.1.1           httpuv_1.6.9            fontLiberation_0.1.0   
[29] curl_5.0.0              fansi_1.0.3             triebeard_0.4.1         urltools_1.7.3         
[33] Rcpp_1.0.10             xtable_1.8-4            openssl_2.0.6           promises_1.2.0.1       
[37] cachem_1.0.7            jsonlite_1.8.4          mime_0.12               systemfonts_1.0.4      
[41] fontBitstreamVera_0.1.1 textshaping_0.3.6       askpass_1.1             digest_0.6.31          
[45] grid_4.2.2              cli_3.6.0               tools_4.2.2             magrittr_2.0.3         
[49] sass_0.4.5              tibble_3.1.8            crul_1.3                crayon_1.5.2           
[53] pkgconfig_2.0.3         ellipsis_0.3.2          rsconnect_0.8.29        data.table_1.14.8      
[57] xml2_1.3.3              assertthat_0.2.1        rmarkdown_2.20          officer_0.6.1          
[61] rstudioapi_0.14.0-9000  R6_2.5.1                compiler_4.2.2

**Comment by davidgohel** [comment]
sorry, I introduced accidentally this issue in the last version.

It should be fixed now with the github version (#[8636510](https://github.com/davidgohel/flextable/commit/86365104f05cfa2ee756f02125b3a224784ee8e6))

**Comment by davidgohel** [comment]
Let me know if it needs to be reopened

**Comment by hjia222** [comment]
@davidgohel Thank you very much for the quick response! Unfortunately, the issue still persist with  flextable_0.9.1.002

> shinyApp(ui = ui, server = server)

Listening on http://127.0.0.1:7996
Warning: Error in curl::curl_fetch_memory: OpenSSL SSL_connect: Connection reset by peer in connection to gwfh.mranftl.com:443 
  119: curl::curl_fetch_memory
  118: crul_fetch
  117: private$make_request
  116: cli$get
  115: get_gf
  114: <Anonymous>
  109: installed_gfonts
  107: avail_gfonts
  104: flextable_html_dependencies
  101: htmltools_value
  100: %>%
   99: renderUI [#4]
   98: func
   85: renderFunc
   84: output$mtcars_ft
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>

> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.0.10        flextable_0.9.1.002 shiny_1.7.4        

loaded via a namespace (and not attached):
 [1] tidyselect_1.2.0        xfun_0.37               bslib_0.4.2             fontquiver_0.2.1       
 [5] vctrs_0.5.2             generics_0.1.3          htmltools_0.5.4         utf8_1.2.2             
 [9] rlang_1.1.0             jquerylib_0.1.4         later_1.3.0             pillar_1.8.1           
[13] withr_2.5.0             DBI_1.1.3               httpcode_0.3.0          glue_1.6.2             
[17] gfonts_0.2.0            gdtools_0.3.2           uuid_1.1-0              lifecycle_1.0.3        
[21] ragg_1.2.5              zip_2.2.2               memoise_2.0.1           evaluate_0.20          
[25] knitr_1.42              fastmap_1.1.1           httpuv_1.6.9            fontLiberation_0.1.0   
[29] curl_5.0.0              fansi_1.0.3             triebeard_0.4.1         urltools_1.7.3         
[33] Rcpp_1.0.10             xtable_1.8-4            openssl_2.0.6           promises_1.2.0.1       
[37] cachem_1.0.7            jsonlite_1.8.4          mime_0.12               systemfonts_1.0.4      
[41] fontBitstreamVera_0.1.1 textshaping_0.3.6       askpass_1.1             digest_0.6.31          
[45] grid_4.2.2              cli_3.6.0               tools_4.2.2             magrittr_2.0.3         
[49] sass_0.4.5              tibble_3.1.8            crul_1.3                crayon_1.5.2           
[53] pkgconfig_2.0.3         ellipsis_0.3.2          rsconnect_0.8.29        data.table_1.14.8      
[57] xml2_1.3.3              assertthat_0.2.1        rmarkdown_2.20          officer_0.6.1          
[61] rstudioapi_0.14.0-9000  R6_2.5.1                compiler_4.2.2

**Comment by davidgohel** [comment]
argh!

What does return the command `curl::has_internet()` on your machine?

**Comment by hjia222** [comment]
> curl::has_internet() 
[1] TRUE

**Comment by davidgohel** [comment]
So you have internet, but you are not allowed to access this url https://gwfh.mranftl.com/fonts?

**Comment by hjia222** [comment]
I see, that might be the issue, I will contact my admin, thanks!

**Comment by davidgohel** [comment]
I will try to fix that in gdtools very soon, will let you know when I will have a solution

**Comment by davidgohel** [comment]
It should be fixed with latest 'gdtools' update - not sure if you can install from github on your platform:

```
remotes::install_github("davidgohel/gdtools")
```

**Comment by hjia222** [comment]
It works now, thank you very much!

**Comment by davidgohel** [comment]
thanks for the feedback @hjia222

**Comment by davidgohel** [comment]
gdtools fix is on cran now
